// Typed access to layout.json (generated by tools/build-layout.mjs from the Wix capture).
import raw from './layout.json';

export interface Box { x: number; y: number; w: number; h: number }
export interface MobileBox { x: number; w: number; h: number; order: number; mt?: number; y?: number; abs?: boolean }
interface Placed { dr: Box; mr?: MobileBox }

export interface TextStyle { font: string; size: number; lh: number | null; weight: string; align: string; color: string; transform: string }
export interface TextNode extends Placed { kind: 'text'; html: string; sd: TextStyle; sm?: { size: number; lh: number | null; align: string } }
export interface ImageNode extends Placed {
  kind: 'image'; image: string; alt: string; frame: boolean; link: string | null;
  lightbox?: string; lightboxIndex?: number; title?: string;
}
export interface CardNode extends Placed { kind: 'card'; radius: number; mobileContents: boolean; mpb?: number; children: ChildNode[] }
export type ChildNode = TextNode | ImageNode | CardNode;
export interface BandNode { kind: 'band'; bg: string; dh: number; mpb?: number; children: ChildNode[] }
export type LayoutNode = BandNode | ChildNode;

export interface PortfolioPage { slug: string; route: string; title: string; docTitle: string; bands: BandNode[] }

export const pages = (raw as unknown as { pages: PortfolioPage[] }).pages;

/** Every image node on a page, depth-first in document order. */
export function imagesOf(page: PortfolioPage): ImageNode[] {
  const out: ImageNode[] = [];
  const walk = (n: LayoutNode) => {
    if (n.kind === 'image') out.push(n);
    if ('children' in n) n.children.forEach(walk);
  };
  page.bands.forEach(walk);
  return out;
}
